version: '3.4'
services:
  client:
    build: ./react-app/
    ports:
      - 3000:3000
    volumes:
      - ./react-app/src/:/app/src/
    links:
      - ipfs-daemon
  ipfs-daemon:
    image: ipfs/go-ipfs
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
    entrypoint:
      - "/bin/sh"
      - -ecx
      - |
        API_ORIGIN=* usr/local/bin/start_ipfs daemon --migrate=true
